### ISSUE TITLE
Pages count is 1 in the first page

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/Pages#19]

**Comment by vadymmarkov** [comment]
Pages count isn't 1 when all the controllers are added and the first page is loaded. But according to this line https://github.com/hyperoslo/Pages/blob/master/Source/PagesController.swift#L193 delegate method is called when we add first controller, so page count is 1 at this moment.

**Comment by 3lvis** [comment]
Closing old issues, since they might not be relevant.
