### ISSUE TITLE
Page remains black

### ISSUE THREAD

**Issue by byroncoetsee** [hyperoslo/Pages#24]
Using the code:

``` Swift
let viewController1 = Tutorial_1_ViewController()
let viewController2 = Tutorial_2_ViewController()
let pages = PagesController([viewController1, viewController2])
self.presentViewController(pages, animated: true, completion: nil)
```

`pages` is displayed, but the page is just black and doesn't allow scrolling. Showing each of the viewControllers individually works correctly so it isn't an issue with them.

Any ideas?

Thanks for the Class though :)

**Comment by richardtop** [comment]
What are the Tutorial_1_ViewController()s ?

**Comment by byroncoetsee** [comment]
All sorted :) I was being an idiot...

**Comment by zenangst** [comment]
@byroncoetsee glad you found the cause of your problem :grin:
