### ISSUE TITLE
More concrete example

### ISSUE THREAD

**Issue by ded** [hyperoslo/Pages#25]
Hi there,
I am intrigued by the simplicity of the example shown in the README. But I'm at a loss as to how to implement any of this. All the example says is to do this:

``` swift
let viewController1 = UIViewController()
viewController1.title = "Controller A"

let viewController2 = UIViewController()
viewController2.title = "Controller B"

let pages = PagesController([viewController1, viewController2])
```

Which left to our own wits, I have no idea where to put this code, or initialize it, _anything_. I've imported the library into my project. Created 3 `ViewControllers` (all through the storyboard) and associated them with their appropriate classes in code.

See below of the setup.

``` swift
// is initial view controller
class Start: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    override func viewDidAppear(animated: Bool) {
        let viewController1 = First()
        let viewController2 = Second()
        let pages = PagesController([viewController1, viewController2])
    }
}

class First: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
    }
}

class Second: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
    }
}
```

All I get is a black screen.

**Comment by ded** [comment]
Hi there. I eventually figured out how to integrate this with my Storyboard ViewControllers with a friends help. Would you be open a pull request that shows a few examples integrating this module into a project?

**Comment by richardtop** [comment]
@ded I would like to see it!

**Comment by ded** [comment]
OK, let me see if I can send something your way in a PR
