### ISSUE TITLE
add Examples screenshot or gif 

### ISSUE THREAD

**Issue by kostiakoval** [hyperoslo/Pages#26]
how it looks like in action ¯_(ツ)_/¯

**Comment by bkawakami** [comment]
+1, not work for me this simple example in readme

**Comment by ded** [comment]
I was confused at first since the code example is more or less pseudo-code, and very unlike a real world situation. The key here is that the `PagesController` returns a ViewController that needs to be presented. So...

``` swift
// ViewController.swift
let storyboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
let vc1: MyViewController = storyboard.instantiateViewControllerWithIdentifier("vc") as! MyViewController
vc1.title = "first"
let vc2: MyViewController = storyboard.instantiateViewControllerWithIdentifier("vc") as! MyViewController
vc2.title = "second"
let pages = PagesController([vc1, vc2])
self.presentViewController(pages)
```

**Comment by bkawakami** [comment]
@ded This code is for a UIViewController or UIPageViewController?

Thank you for your example!

**Comment by bkawakami** [comment]
@ded not work with a UINavigationBar :(

**Comment by richardtop** [comment]
@bkawakami could you explain the result you're trying to achieve? Or provide a screenshot? Then I may try to help you.

**Comment by ded** [comment]
these can be regular `ViewControllers` — a navigationbar or NavigationController is not necessary.

**Comment by vadymmarkov** [comment]
Now there is a gif in README and you always can check the example project we have: https://github.com/hyperoslo/Pages/tree/master/Example/PagesDemo
