### ISSUE TITLE
pages outside of startPage property still accessible even after setting property

### ISSUE THREAD

**Issue by jurvis** [hyperoslo/Pages#40]
Since `startPage` is a public property on PagesViewController, I assume that it's meant to be available to developers to change and enforce a start page during runtime? 

I noticed that when your `currentIndex = 0` and if you set startPage to 1, the page at index 0 is still accessible as usual. 

Not sure if it's a behaviour worth considering adding but I've created quick PR #39 to fix that

**Comment by vadymmarkov** [comment]
@jurvis Sorry for a super long reply, we kind of missed this issue and your PR. I think `startPage` was made mutable by mistake, now it's a `let` constant. Thanks for contribution anyway 🚀

**Comment by jurvis** [comment]
@vadymmarkov no worries, thanks for taking a look at the PR! love these changes for `1.0.0`!
