### ISSUE TITLE
Example customizing page control

### ISSUE THREAD

**Issue by kiokumicu** [hyperoslo/Pages#41]
Maybe you add example how to customize UIPageControl ? 
Change background color, indicators color etc.

**Comment by movch** [comment]
Approach that worked for me: to customise it globally in application's didFinishLaunchingWithOptions, e.g.:

```
let pageControlAppearance = UIPageControl.appearance()
pageControlAppearance.pageIndicatorTintColor = UIColor.lightGrayColor()
pageControlAppearance.currentPageIndicatorTintColor = UIColor(red: 249/255, green: 48/255, blue: 109/255, alpha: 1.0)
```

But I would like to see more elegant solution as well...
