### ISSUE TITLE
iOS 11 iPhone X UI problem

### ISSUE THREAD

**Issue by chonex143** [hyperoslo/Pages#48]
When trying to go back in viewcontroller the UI will goes like this:

![simulator screen shot - iphone x - 2017-09-21 at 10 10 23](https://user-images.githubusercontent.com/25475522/30675831-69c0ae62-9eb5-11e7-9677-0bc88e927e91.png)

**Comment by onmyway133** [comment]
@chonex143 Hi, thanks for raising the issue. We will note this in the Swift 4 migration

**Comment by vadymmarkov** [comment]
@chonex143 @onmyway133 The thing is that we don't modify `UIPageControl` position so I'm pretty sure you would get the same using plain `UIPageViewController`.

**Comment by mmoloksher** [comment]
FYI I had something similar happen to my UIPageViewController on the iPhone X. It turned out to be that the image in the view controller was actually wider than the UIPageViewController. Checking ON Clip To Bounds on the view controller did it for me.
