### ISSUE TITLE
Xcode 10

### ISSUE THREAD

**Issue by hgado11** [hyperoslo/Pages#59]
Hello,

I got the following error with XCODE 10:

<unknown>:0: error: fatal error encountered while reading from module 'Pages'; please file a bug report with your project and the crash log
<unknown>:0: note: compiling as Swift 4.2, with 'Pages' built as Swift 4.1.50 (this is supported but may expose additional compiler issues)

1.	While running pass #1 SILModuleTransform "PerformanceSILLinker".
2.	While deserializing SIL vtable for 'PagesController' in module 'Pages'
error: Abort trap: 6

**Comment by Kleemann** [comment]
You might just be better suited with rewriting to use UIPageViewController. 
If that's not possible for you try [this fix on my fork](https://github.com/Kleemann/Pages/commit/941d5d2adcd3fadbd58c9cb2eb9e7897adbd27fc), and see if it helps.

**Comment by alexookah** [comment]
had the same issue
i checked the PR and it seems it's working :)
well done @hgado11
